# Generated by Django 3.0.6 on 2020-07-26 15:17

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='place_information',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('place_image', models.ImageField(upload_to='photos')),
                ('place_name', models.CharField(max_length=255)),
                ('place_description', models.TextField()),
                ('place_longitude', models.FloatField()),
                ('place_latitude', models.FloatField()),
                ('place_ratings', models.IntegerField()),
                ('place_type', models.CharField(max_length=100)),
                ('end_datetime', models.DateTimeField(blank=True, default=None, null=True)),
                ('added_by', models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
