# Generated by Django 3.0.6 on 2020-07-26 15:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('application', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='place_information',
            name='end_datetime',
            field=models.DateTimeField(default=None, null=True),
        ),
    ]
