# Generated by Django 3.0.6 on 2020-07-26 15:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('application', '0002_auto_20200726_0832'),
    ]

    operations = [
        migrations.AlterField(
            model_name='place_information',
            name='end_datetime',
            field=models.DateTimeField(default='1999-09-09 00:00:00', null=True),
        ),
    ]
