# Generated by Django 3.0.6 on 2020-07-26 15:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('application', '0003_auto_20200726_0840'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='place_information',
            name='end_datetime',
        ),
    ]
