# Generated by Django 3.2.8 on 2022-02-05 11:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('application', '0004_remove_place_information_end_datetime'),
    ]

    operations = [
        migrations.DeleteModel(
            name='place_information',
        ),
    ]
