# Generated by Django 3.2.8 on 2022-02-05 15:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('application', '0006_user'),
    ]

    operations = [
        migrations.DeleteModel(
            name='User',
        ),
    ]
