# Generated by Django 3.2.8 on 2022-02-06 13:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('application', '0009_auto_20220206_1444'),
    ]

    operations = [
        migrations.CreateModel(
            name='Term',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('typee', models.CharField(choices=[('Word', 'word'), ('Phrase', 'phrase'), ('Term', 'Term')], max_length=10)),
                ('content', models.TextField()),
                ('category', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='application.category')),
                ('topics', models.ManyToManyField(to='application.Topic')),
            ],
        ),
    ]
