# Generated by Django 3.2.8 on 2022-02-06 14:46

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('application', '0010_term'),
    ]

    operations = [
        migrations.AddField(
            model_name='term',
            name='created_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='term',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='term',
            name='typee',
            field=models.CharField(choices=[('Word', 'Word'), ('Phrase', 'Phrase'), ('Term', 'Term')], max_length=10),
        ),
    ]
