# Generated by Django 3.2.8 on 2022-03-06 11:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('application', '0015_folder'),
    ]

    operations = [
        migrations.AddField(
            model_name='term',
            name='folder',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='application.folder'),
        ),
    ]
