# Generated by Django 3.2.8 on 2022-03-06 14:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('application', '0016_term_folder'),
    ]

    operations = [
        migrations.AddField(
            model_name='bookmark',
            name='color',
            field=models.CharField(choices=[('yellow', '#EEF43B')], default='yellow', max_length=50),
        ),
    ]
