# Generated by Django 3.2.8 on 2022-03-06 14:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('application', '0017_bookmark_color'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bookmark',
            name='color',
            field=models.CharField(choices=[('#EEF43B', 'yellow')], default='yellow', max_length=50),
        ),
    ]
