# Generated by Django 3.2.8 on 2022-03-06 15:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('application', '0018_alter_bookmark_color'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bookmark',
            name='color',
            field=models.CharField(choices=[('yellow', 'Yellow'), ('green', 'Green'), ('blue', 'Blue'), ('purple', 'Purple'), ('red', 'Red')], default='yellow', max_length=50),
        ),
    ]
