# Generated by Django 3.2.8 on 2022-03-06 16:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('application', '0019_alter_bookmark_color'),
    ]

    operations = [
        migrations.AddField(
            model_name='bookmark',
            name='comment',
            field=models.TextField(blank=True, null=True),
        ),
    ]
