# Generated by Django 3.2.8 on 2022-03-09 19:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('application', '0021_device'),
    ]

    operations = [
        migrations.AlterField(
            model_name='device',
            name='datetime',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
