# Generated by Django 3.2.8 on 2022-03-09 19:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('application', '0022_alter_device_datetime'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Device',
        ),
    ]
