# Generated by Django 3.2.8 on 2022-03-09 20:04

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('application', '0024_device'),
    ]

    operations = [
        migrations.AddField(
            model_name='device',
            name='last_login',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
