# Generated by Django 3.2.8 on 2022-03-16 20:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('application', '0025_device_last_login'),
    ]

    operations = [
        migrations.CreateModel(
            name='Training',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('description', models.CharField(max_length=255)),
                ('thumbnail', models.ImageField(upload_to='thumbnails/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Module',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('description', models.CharField(max_length=255)),
                ('thumbnail', models.ImageField(upload_to='thumbnails/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('next', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mod_next', to='application.module')),
                ('prev', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mod_prev', to='application.module')),
                ('training', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='application.training')),
            ],
        ),
        migrations.CreateModel(
            name='Media',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('description', models.CharField(max_length=255)),
                ('thumbnail', models.ImageField(upload_to='thumbnails/')),
                ('file', models.FileField(upload_to='files/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('module', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='application.module')),
                ('next', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='file_next', to='application.media')),
                ('prev', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='file_prev', to='application.media')),
            ],
        ),
    ]
