# Generated by Django 3.2.8 on 2022-03-18 10:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('application', '0026_media_module_training'),
    ]

    operations = [
        migrations.AlterField(
            model_name='media',
            name='file',
            field=models.URLField(),
        ),
    ]
