# Generated by Django 3.2.8 on 2022-03-18 10:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('application', '0027_alter_media_file'),
    ]

    operations = [
        migrations.AlterField(
            model_name='media',
            name='next',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='file_next', to='application.media'),
        ),
        migrations.AlterField(
            model_name='media',
            name='prev',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='file_prev', to='application.media'),
        ),
        migrations.AlterField(
            model_name='module',
            name='next',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='mod_next', to='application.module'),
        ),
        migrations.AlterField(
            model_name='module',
            name='prev',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='mod_prev', to='application.module'),
        ),
    ]
