# Generated by Django 3.2.8 on 2022-03-18 10:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('application', '0028_auto_20220318_1026'),
    ]

    operations = [
        migrations.AlterField(
            model_name='training',
            name='description',
            field=models.TextField(),
        ),
    ]
